// Generated by CoffeeScript 1.3.1
(function() {

  window.TimeSlot = function(data) {
    var _ref, _ref1;
    this.id = ko.observable((_ref = data != null ? data.id : void 0) != null ? _ref : '');
    this.title = ko.observable((_ref1 = data != null ? data.time : void 0) != null ? _ref1 : '');
    this.sessions = ko.observableArray();
    return this;
  };

}).call(this);
